// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxsTx4sYRCnEsvhcjYbkNzonxo_QFVrw',
    appId: '1:1006759060995:web:4042fd246305b072f35036',
    messagingSenderId: '1006759060995',
    projectId: 'campus361-351bb',
    authDomain: 'campus361-351bb.firebaseapp.com',
    storageBucket: 'campus361-351bb.firebasestorage.app',
    measurementId: 'G-EL5MH9HP5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6l1cTdYtWd4KW_jfxIq8-ov9DOCOB8w',
    appId: '1:1006759060995:android:8b25c654aae4053ef35036',
    messagingSenderId: '1006759060995',
    projectId: 'campus361-351bb',
    storageBucket: 'campus361-351bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS2MFCSa0UjAdOO93aYi4UnxZ9RaoLoYo',
    appId: '1:1006759060995:ios:a6dedc9e4b77edb3f35036',
    messagingSenderId: '1006759060995',
    projectId: 'campus361-351bb',
    storageBucket: 'campus361-351bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS2MFCSa0UjAdOO93aYi4UnxZ9RaoLoYo',
    appId: '1:1006759060995:ios:a6dedc9e4b77edb3f35036',
    messagingSenderId: '1006759060995',
    projectId: 'campus361-351bb',
    storageBucket: 'campus361-351bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUxsTx4sYRCnEsvhcjYbkNzonxo_QFVrw',
    appId: '1:1006759060995:web:e30b8749fa4593ccf35036',
    messagingSenderId: '1006759060995',
    projectId: 'campus361-351bb',
    authDomain: 'campus361-351bb.firebaseapp.com',
    storageBucket: 'campus361-351bb.firebasestorage.app',
    measurementId: 'G-Q7FSVJWBW7',
  );
}
